name: federated-monorepo
services:

  ## 1st provider
  provider-one:
    build:
      context: ../../src/packages/provider-one
      dockerfile: docker/dockerfile/Dockerfile
    ports:
      - "3001:3001"
    image: provider-one:0.1.0
    container_name: provider-one
    networks:
      - local-network

  ## 2nd provider
#  provider-two:
#    build:
#      context: ./src/packages/provider-two
#    ports:
#      - "3002:3002"
#    image: provider-two:0.1.0
#    container_name: provider-two
#    networks:
#      - local-network

  # shell/consumer application
  consumer:
    build:
      context: ../../
      dockerfile: docker/dockerfile/Dockerfile (standard)
    ports:
      - "3000:3000"
    image: consumer-app:0.1.0
    container_name: consumer-app
    networks:
      - local-network
    depends_on:
      - provider-one
#      - provider-two

networks:
  local-network:
    driver: bridge